CREATE TABLE Accounts (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  address_id INT NOT NULL,
  is_owner TINYINT(1) NOT NULL,
  is_producer TINYINT(1) NOT NULL,
  FOREIGN KEY (address_id) REFERENCES Addresses(id) ON DELETE CASCADE
);
