CREATE TABLE Cinemas (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address_id INT NOT NULL,
  owner_id INT NOT NULL,
  FOREIGN KEY (address_id) REFERENCES Addresses(id) ON DELETE CASCADE,
  FOREIGN KEY (owner_id) REFERENCES Accounts(id) ON DELETE CASCADE
);
