CREATE TABLE Showings (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  theater_id INT NOT NULL,
  movie_id INT NOT NULL,
  show_date DATE NOT NULL,
  show_time TIME NOT NULL,
  price INT NOT NULL,
  FOREIGN KEY (theater_id) REFERENCES Theaters(id) ON DELETE CASCADE,
  FOREIGN KEY (movie_id) REFERENCES Movies(id) ON DELETE CASCADE
);
